Added template as volume and validation for its format

diff --git a/Server/Dockerfile b/Server/Dockerfile
--- a/Server/Dockerfile
+++ b/Server/Dockerfile
@@ -3,15 +3,18 @@ FROM golang:alpine3.22@sha256:20c8a94b529a9a127b6990c5e03537bd71ce3ebfdd744741e9
 WORKDIR /app/Server
 
 COPY db/initial.db /app/Server/db/my.db
-
 COPY go.mod go.sum ./
 
 RUN go mod download
 
 COPY . .
 
+RUN go build -o /app/Server/validateJson ./Validate
+RUN chmod +x /app/Server/validateJson
+
 RUN go build -v -o server
 
-EXPOSE 80
+RUN /app/Server/validateJson /app/Server/template.json || (echo "JSON validation failed." && exit 1)
 
+EXPOSE 80
 CMD [ "./server" ]
